"""test3

Revision ID: 93d94f503ee7
Revises: 8c32c93a86f9
Create Date: 2026-04-11 17:55:23.283110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93d94f503ee7'
down_revision: Union[str, None] = '8c32c93a86f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###